language: python
python:
  - 3.7

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.4.2

before_install:
  - python --version
  - pip install -U pip
  - pip install pytest

before_deploy:
  - curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
  - heroku --version

script: pytest

jobs:
  include:
    - stage: build
      script:
        - docker build -t smart-vit/feedback-service .
        - docker ps -a
    - stage: test
      script:
        - flake8
        - coverage run -m pytest
        - coverage xml
    - stage: deploy-dev
      if: branch = devel
      script:
        - export MONGOPASSWORD=${MONGOPASSWORD}
        - export DBNAME=${DBNAMESTG}
        - export ENVIRONMENT=${ENVSTG}
        - docker-compose build
        - docker images -a
        - bash docker_push.sh
    - stage: deploy-stg
      if: branch = feature/cd_configuration
      script:
        - export MONGOPASSWORD=${MONGOPASSWORD}
        - export DBNAME=${DBNAMESTG}
        - export ENVIRONMENT=${ENVSTG}
        - docker-compose build
        - bash docker_push.sh
    - stage: deploy-prd
      if: branch = master
      script:
        - export MONGOPASSWORD=${MONGOPASSWORD}
        - export DBNAME=${DBNAMEPRD}
        - export ENVIRONMENT=${ENVPRD}
        - docker-compose build
        - bash docker_push.sh

after_success:
  - python-codacy-coverage -r coverage.xml
