language: python
python:
  - 2.7
  - 3.5

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.4.2

before_install:
  - python --version
  - pip install -U pip
  - pip install -r pytest

jobs:
  include:
      - stage: build
        script: 
          - docker build -t smart-vit/feedback-service
      - stage: test
          - pytest

