language: python
python:
  - 3.7

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.4.2

before_install:
  - python --version
  - pip install -U pip
  - pip install pytest
  - sudo apt-get install jq
  - curl -LSs "$(curl -LSs https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r '.assets | map({name, browser_download_url} | select(.name | endswith(".jar"))) | .[0].browser_download_url')" -o codacy-coverage-reporter-assembly.jar

script: pytest
  
jobs:
  include:
      - stage: build
        script: 
          - docker build -t smart-vit/feedback-service .
      - stage: test
        script: 
          - flake8
          - coverage run -m pytest


after_success:
  - java -jar codacy-coverage-reporter-assembly.jar report -l Java -r build/reports/jacoco/test/jacocoTestReport.xml

