language: python
python:
  - 3.7

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.4.2

before_install:
  - python --version
  - pip install -U pip
  - pip install pytest

before_deploy:
  - curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
  - export MONGOPASSWORD=${MONGOPASSWORD}
  - export DBNAME=${DBNAMEDEV}
  - export ENVIRONMENT=${ENVDEV}

script: pytest

jobs:
  include:
    - stage: build
      script:
        - docker build -t smart-vit/feedback-service .
        - docker ps -a
    - stage: test
      script:
        - flake8
        - coverage run -m pytest
        - coverage xml

deploy:
  - provider: heroku
    api_key:
      secure: ${API_HERO}
    app: feedback-service-stg
    script:
      - export MONGOPASSWORD=${MONGOPASSWORD}
      - export DBNAME=${DBNAMESTG}
      - export ENVIRONMENT=${ENVSTG}
      - docker-compose build
      - docker images -a
      - bash docker_push.sh
      - heroku container:login
      - heroku stack:set container
      - heroku container:push feedback-service
      - heroku container:release feedback-service
    on:
      branch: feature/cd_configuration
after_success:
  - python-codacy-coverage -r coverage.xml
