language: python
python:
  - 3.5
  - 3.6
  - 3.7

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.4.2

before_install:
  - python --version
  - pip install -U pip
  - pip install pytest
  
jobs:
  include:
      - stage: build
        script: 
          - docker build -t smart-vit/feedback-service
      - stage: test
        script:
          - pytest

